### ISSUE TITLE
Standardize SQL organization and naming conventions

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1240]
# Problem Statement
The SQL files associated with each layer are inconsistently named and organized.  In some cases, file names don't match file contents (for example, generalized table definitions are sometimes placed in an "update" file).  Some of this is likely a historical artifact of past versions.  For example, there are various places where "merge" is found in table names and file names yet no obvious merging is occurring.  This adds up to making the codebase challenging for new developers to understand.  This issue proposes to re-organize the SQL files with standard naming conventions and redistribute the contents to match in order to increase the maintainability and understandability of the SQL code going forward.

As a recent new developer myself, I found the code challenging to understand.  The inclusion of generalized tables in files with "update" in the name, for example, was confusing and made it hard to find what I was looking for.  It wasn't obvious which things were defined in _layername_update.sql_ versus _layername.sql_.

In addition, given the recent discussions related to project organization, such as #1183, #1178, #1238, and openmaptiles/openmaptiles-tools#368, it seems that the time is ripe to improve our file organization before further expanding the number of layers in the project.

## Proposed Organization

The SQL loading process associated with layers can be described in the following sequence:

1. Imposm mappings generate a series of base tables directly from OSM data
2. Custom types and enumerations specific to this layer are defined
3. Post-processing is performed on the initial imposm data load
4. Generalized tables are defined which create zoom-specific approximations of the layer data at each zoom using PostGIS functions such as `ST_Simplify`
5. Update collector tables and triggers are defined such that updates to the imposm-generated tables trigger updates to all computed tables and views
6. The layer generation function is defined

Note that not all layers will have all of the steps described above; some will be simpler.

It is proposed that SQL files be divided into the following namespaces:
1. **def** - for layer definitions, types, and enumerations
2. **proc** - for post-processing of imposm-generated tables
3. **gen** - for defining generalized tables
4. **update** - for defining update tables and triggers
5. **layer** - for the layer definition

In some cases, we may find that a name-spaced SQL file is large enough that it makes sense to divide them into multiple files.  In that case, the naming convention would be to add an optional suffix to distinguish them.

The proposed naming convention is thus:
**&lt;layer_name&gt;\_&lt;namespace&gt;\_&lt;optional_suffix&gt;.sql**

Thus, the update code for the "park" layer would be found in `park_update.sql`, and the generalized tables for geometries in the transportation layer would be found in `transportation_gen.sql`.

We may also consider as an alternate approach to suppress the **&lt;layer_name&gt;** portion of the filename, as it is redundant with the parent folder name.

## Tasks

- [ ] Document SQL file organization
- [ ] Reorganize layer `aerodrome_label`
- [ ] Reorganize layer `aeroway`
- [ ] Reorganize layer `boundary`
- [ ] Reorganize layer `building`
- [ ] Reorganize layer `housenumber`
- [ ] Reorganize layer `landcover`
- [ ] Reorganize layer `landuse`
- [ ] Reorganize layer `mountain_peak`
- [ ] Reorganize layer `park`
- [ ] Reorganize layer `place`
- [ ] Reorganize layer `poi`
- [ ] Reorganize layer `transportation`
- [ ] Reorganize layer `transportation_name`
- [ ] Reorganize layer `water`
- [ ] Reorganize layer `water_name`
- [ ] Reorganize layer `waterway`

The scale of the proposed changes likely means a reorganization should wait until the version 4.0 major version upgrade.  While this change is not specifically "breaking", it is likely to cause considerable impact on downstream forks to match the new organization.  In addition, layer reorganizations should wait for times when there are no open PRs for the layer in question.

This issue is offered as a focal point for discussion standardization of the SQL layer.

**Comment by zstadler** [comment]
Adding to the above description

`make build-sql` fills the the `build/sql` directory with the files required for `make import-sql`:

- The `build/sql/run_first.sql` file is imported before all other files. Currently it defines the `slice_language_tags()` function for use by all the layers.
- The files in the `build/sql/parallel` directory are imported in parallel, with no more than `MAX_PARALLEL_PSQL` imports in a given time.
  - Usually, the SQL files of each layer are included in a single file named `build/sql/parallel/<layer>.sql`. Comments are added to the file to indicate the origin of the code. For example:
     ```
      -- Layer park - ./update_park_polygon.sql
      ```
  - When there is a dependencies between layers, such as between the `transportation` and the `transportation_name` layers, the SQL code for the layers is placed in one file that preserves the order of the dependency. For example, the `build/sql/parallel/transportation__transportation_name.sql` file includes the code of the `transportation` and the `transportation_name` layers, in this order.
- The `build/sql/run_last.sql` file is imported after all other file. Currently it defines the `getmvt()` function using all the layer generation functions.

I'm not sure this has any impact on this proposal, other than the ability to include the descriptions in the documentation.
