### ISSUE TITLE
Installation Fails June 1, 2024 with: error: function getmvt

### ISSUE THREAD

**Issue by jlpoolen** [openmaptiles/openmaptiles#1662]
I followed the installation instructions using docker in Debian.  (I had previously tried in Gentoo and received a failure, so decided to try your install on Debian which is fully supported.)

```

jlpoole@debian1:/usr/local/src/openmaptiles$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
jlpoole@debian1:/usr/local/src/openmaptiles$ 
```
```

jlpoole@debian1:/usr/local/src/openmaptiles$ sudo make generate-tiles-pg
Using docker compose V2 (docker compose)
docker compose run --rm --user=0:0 openmaptiles-tools bash -c 'style-tools recompose openmaptiles.yaml build/style/style.json \
	style/style-header.json && \
	spreet /style/icons build/style/sprite && spreet --retina /style/icons build/style/sprite@2x'
WARN[0000] /usr/local/src/openmaptiles/docker-compose.yml: `version` is obsolete 
Starting postgres docker compose target using default image (no recreate if exists)
WARN[0000] /usr/local/src/openmaptiles/docker-compose.yml: `version` is obsolete 
[+] Running 1/0
 ✔ Container openmaptiles-postgres-1  Running                              0.0s 
Wait for PostgreSQL to start...
docker compose run --rm --user=0:0 openmaptiles-tools pgwait
WARN[0000] /usr/local/src/openmaptiles/docker-compose.yml: `version` is obsolete 
Generating tiles into data/tiles.mbtiles (will delete if already exists) using PostGIS ST_MVT()...
docker compose run -T --rm --user=0:0 openmaptiles-tools generate-tiles
WARN[0000] /usr/local/src/openmaptiles/docker-compose.yml: `version` is obsolete 
2024-06-01 13-24-18 Generating zoom 0..7 inside (18.89648,39.62738,21.06285,42.66313) from 1 servers, using 10 connections per server, 10 parallel streams...
+ tilelive-copy --scheme=pyramid --bounds=18.89648,39.62738,21.06285,42.66313 --minzoom=0 --maxzoom=7 --timeout=1800000 --exit --retry=2 --concurrency=10 'pgquery://?database=openmaptiles&host=postgres&port=5432&username=openmaptiles&password=openmaptiles&funcZXY=getmvt&maxpool=10&minzoom=0&maxzoom=14' mbtiles:///export/tiles.mbtiles
tilelive-pgquery v1.2.0
Tilejson Spec:
       tilejson = 2.1.0
           name = PgQuery 1.2.0
         format = pbf
             id = openmaptiles
    attribution = <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>
         bounds = -180,-85.0511,180,85.0511
         center = -12.2168,28.6135,4
        minzoom = 0
        maxzoom = 14
    pixel_scale = 256
      maskLevel = 8
        version = 3.9

Server information for postgres:5432:
                         version() = PostgreSQL 14.9 (Debian 14.9-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
            postgis_full_version() = POSTGIS="3.3.4 3.3.4" [EXTENSION] PGSQL="140" GEOS="3.9.0-CAPI-1.16.2" PROJ="7.2.1" LIBXML="2.9.10" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)"
                               jit = off
                    shared_buffers = 128MB
                          work_mem = 4MB
              maintenance_work_mem = 64MB
              effective_cache_size = 4GB
          effective_io_concurrency = 1
                   max_connections = 100
              max_worker_processes = 8
              max_parallel_workers = 8
   max_parallel_workers_per_gather = 2
                       wal_buffers = 4MB
                      min_wal_size = 80MB
                      max_wal_size = 1GB
                  random_page_cost = 4
         default_statistics_target = 100
      checkpoint_completion_target = 0.9

Verifying pgquery data source by retrieving a tile at [14,9268,3575] from postgres:5432/openmaptiles...
Failed to get a tile at [14,9268,3575] from postgres:5432/openmaptiles (in 4ms), aborting tilelive-pgquery initialization:
error: function getmvt(unknown, unknown, unknown) does not exist
/usr/local/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

error: function getmvt(unknown, unknown, unknown) does not exist
    at /usr/local/lib/node_modules/tilelive-pgquery/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PgQuery._getRawTileAsync (/usr/local/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:283:19)
    at async PgQuery._testSingleServer (/usr/local/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:431:19)
    at async Promise.all (index 0)
    at async PgQuery.testOnStartupAsync (/usr/local/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:489:21)
    at async PgQuery.init (/usr/local/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:117:7) {
  length: 226,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '34',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '629',
  routine: 'ParseFuncOrColumn'
}

Node.js v18.19.0
make: *** [Makefile:471: generate-tiles-pg] Error 1
jlpoole@debian1:/usr/local/src/openmaptiles$ 
```

**Comment by jlpoolen** [comment]
On a separate server (Gentoo based vs. Debian), I found where getmvt is referenced.  This may help readers unfamiliar with the code and suggests a possible issue regarding order of execution of installation scripts?

```
jlpoole@ryzdesk /usr/local/src/openmaptiles $ find .  -type f |xargs grep getmvt
./Makefile:                                                      --function --fname=getmvt >> ./build/sql/run_last.sql'
./quickstart.log:                                                --function --fname=getmvt >> ./build/sql/run_last.sql'
./build/sql/run_last.sql:DROP FUNCTION IF EXISTS getmvt(integer, integer, integer);
./build/sql/run_last.sql:CREATE FUNCTION getmvt(zoom integer, x integer, y integer)
jlpoole@ryzdesk /usr/local/src/openmaptiles $ 
```

**Comment by jlpoolen** [comment]
My [User] error.  **I failed to execute the step**:  "make import-wikidata"

Here is a record of my install where I identified my omission.  This approach may be helpful for other who log issues and can demonstrate they followed the correct sequence of events.

Based on line numbers ("#[xxx]") at this paste:
  https://pastebin.com/YukmGx61

- [x] git clone https://github.com/openmaptiles/openmaptiles.git && cd openmaptiles #1
- [x] make #10
- [x] make start-db #36
- [x] make import-data #72
- [x] make download area=albania #107
- [x] make import-osm #135
- [x] make import-wikidata  (DID NOT PERFORM -- overlooked?)
- [x] make build-style #176
- [x] make generate-bbox-file #182
- [x] make generate-tiles-pg #186

I found the section "_Workflow to generate tiles_" at the end of the README.md and followed that and successfully completed the task of loading Albania.
