### ISSUE TITLE
update-osm taking a long time to import even small planet hangesets (Postgres COMMIT slow)

### ISSUE THREAD

**Issue by skylarmt** [openmaptiles/openmaptiles#814]
When using update-osm to import daily changesets, there are about five or ten minutes of "work" being done, followed by six to twelve hours where the import time increases, nothing else changes, and Postgres is pegging a single core at 100%, doing something to the disk at around 80+ megabytes per second, and appearing to just hang.

I also tried to import an hourly changeset (they're only a couple megabytes!) and killed it at the one hour mark; it was behaving the same as for the daily changesets.

This is the kind of output I've been getting:

```
skylar@mapbeast:~/openmaptiles$ docker-compose run --rm update-osm
[Apr 20 00:00:50] [INFO] [diff] Parsing changes, updating cache and removing elements took: 13.908048514s
[Apr 20 00:00:50] [INFO] [   13s] C:    8000/s (44702) N:     100/s (790) W:    1000/s (8643) R:      0/s (328)
[Apr 20 00:00:59] [INFO] [PostGIS] Updating generalized tables took: 1.550812465s
[Apr 20 00:01:50] [INFO] [  1m0s] C:       0/s (0) N:    1700/s (1709) W:     900/s (5612) R:    180/s (104)
[Apr 20 00:02:50] [INFO] [  2m0s] C:       0/s (0) N:    1700/s (1709) W:     900/s (5612) R:    180/s (104)
[Apr 20 00:03:50] [INFO] [  3m0s] C:       0/s (0) N:    1700/s (1709) W:     900/s (5612) R:    180/s (104)
[Apr 20 00:04:50] [INFO] [  4m0s] C:       0/s (0) N:    1700/s (1709) W:     900/s (5612) R:    180/s (104)
[Apr 20 00:05:50] [INFO] [  5m0s] C:       0/s (0) N:    1700/s (1709) W:     900/s (5612) R:    180/s (104)
[Apr 20 00:06:50] [INFO] [  6m0s] C:       0/s (0) N:    1700/s (1709) W:     900/s (5612) R:    180/s (104)
[Apr 20 00:07:50] [INFO] [  7m0s] C:       0/s (0) N:    1700/s (1709) W:     900/s (5612) R:    180/s (104)
[Apr 20 00:08:50] [INFO] [  8m0s] C:       0/s (0) N:    1700/s (1709) W:     900/s (5612) R:    180/s (104)
...etc, etc, etc...
```

My server has four physical CPUs, 48 threads, 80GB RAM, and the database is on two PCIe SSDs in RAID0.  I have read nearly every Postgres optimization blog post on the Internet and none of them have helped.  I'm starting to think that it might not be my server's fault, which is why I'm posting this.

**Comment by frodrigo** [comment]
It is how OpenMapTiles works for now.
On each update you have to regenerate materialized views for the whole planet. No matter the size of your diff.

**Comment by skylarmt** [comment]
Is there perhaps a way to not regenerate those views after each update, then manually trigger the update after a series of imports?

**Comment by nyurik** [comment]
This is similar to https://github.com/openmaptiles/openmaptiles/issues/809 , and could use the same solution.

**Comment by nyurik** [comment]
Also, take a look at the https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/refresh-views tool

**Comment by frodrigo** [comment]
Overview of parts to improve for quicker diff update

Simple Update on full table:
- [x] update_peak_point.sql #896
- [ ] update_city_point.sql
- [ ] update_state_point.sql
- [ ] update_island_polygon.sql
- [ ] update_island_point.sql
- [ ] update_continent_point.sql
- [ ] housenumber_centroid.sql
- [ ] update.sql (aerodrome_label)

Complexe Update on full table
- [ ] update_country_point.sql
- [ ] update_poi_polygon.sql
- [ ] update_marine_point.sql

Simple Materialized view
- [x] update_water_lakeline.sql #853
- [x] update_water_point.sql #853

Complexe Materialized view
- [x] update_important_waterway.sql #853
- [ ] update_transportation_name.sql (partial: #892)
- [ ] update_poi_point.sql
- [ ] update_transportation_merge.sql
- [ ] update_route_member.sql

**Comment by agoddard** [comment]
@skylarmt @nyurik is this resolved now? I'm seeing each daily planet update take around 45min on a fairly basic system (running on master)

```
[Feb 10 21:38:52] [INFO] [diff] Processing /import/000/003/073.osc.gz took: 46m18.918127466s
[Feb 10 21:38:53] [INFO] importing #3073 till 2021-02-10 00:00:00 +0000 UTC took: 46m19.792423804s
```

**Comment by frodrigo** [comment]
As you can see by the long list of commit here, it was largely improved in the last release, but not fully solved yet.

**Comment by agoddard** [comment]
@frodrigo actually is it possible that this will be very different based on whether `import-sql` was run before `update-osm`? I think that maybe once the indexes etc are added, the `update-osm` process slows down significantly

**Comment by frodrigo** [comment]
> @frodrigo actually is it possible that this will be very different based on whether `import-sql` was run before `update-osm`? I think that maybe once the indexes etc are added, the `update-osm` process slows down significantly

Yes. `import-sql` create index, triggers to update deviated tables and more over materialized view recomputed on each update.

**Comment by agoddard** [comment]
@frodrigo given the significant difference between running `update-osm` before and after `import-sql`, would there be a downside to the following workflow?

1) Server A: `import-osm`
2)Server A: `update-osm` to catch up
3) copy database to second Server B
4) Server B: `import-sql` 
5) Server A: `update-osm` to catch up

and then basically repeating steps 3-5 whenever you want to prepare the DB for serving or generating tiles?
