### ISSUE TITLE
Cleanup name field naming and meaning

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#930]
There are several issues with how we currently handle multilingual names. This is an umbrella ticket to track them all, and decide on a general strategy.

- [ ] Remove `name_de` and `name_en` (first mentioned in #769, implemented in #928)
- [ ] Rename `name:latin` -> `name_latin` or `name-Latn` or ???
- [ ] Rename `name:nonlatin` -> `name_nonlatin` or ???
- [ ] Document the usage of `name_int`
- [ ] Handle OSM's Korean names - almost no [name:ko_rm](https://taginfo.openstreetmap.org/search?q=name%3Ako_rm), a lot of [name:ko-Latn](https://taginfo.openstreetmap.org/search?q=name%3Ako-Latn) - see #537 
- [ ] Handle OSM's Japanese names -- 100,000 of [name:ja_rm](https://taginfo.openstreetmap.org/search?q=name%3Aja_rm), but they are deprecated per wiki in favor of [name:ja-Latn](https://taginfo.openstreetmap.org/search?q=name%3Aja-Latn) (about 50,000) - was also mentioned in #537

**Comment by systemed** [comment]
It would be good to have clarity on this, and for frequently used styles to be updated to match. Right now it's entirely unclear what third-party implementations of the OMT schema are meant to support - the spec says `name`, `name_en` and `name_de`, but styles appear to use `name:latin` or whatever.
